services:
  lb:
    image: nginx:latest
    ports:
      - 9999:9999

    networks:
      - pyrinha
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2

    deploy:
      resources:
        limits:
          cpus: 0.20
          memory: 40MB

  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - cache
    networks:
      - pyrinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 105MB
    environment:
      DEFAULT_PAYMENT_PROCESSOR: "http://payment-processor-default:8080"
      FALLBACK_PAYMENT_PROCESSOR: "http://payment-processor-fallback:8080"

  api2:
    <<: *api
    ports:
      - 8082:8080
  
  cache:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - pyrinha
    deploy:
      resources:
        limits:
          cpus: 0.30
          memory: 100MB

networks:
  pyrinha:
    driver: bridge
  payment-processor:
    external: true