services:
  lb:
    image: nginx:latest
    ports:
      - 9999:9999

    networks:
      - pyrinha
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2

    deploy:
      resources:
        limits:
          cpus: 0.20
          memory: 20MB

  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - cache
    networks:
      - pyrinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 160MB
    environment:
      DEFAULT_PAYMENT_PROCESSOR: "http://payment-processor-default:8080"
      FALLBACK_PAYMENT_PROCESSOR: "http://payment-processor-fallback:8080"

  api2:
    <<: *api
    ports:
      - 8082:8080
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 160MB

  cache:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - pyrinha
    deploy:
      resources:
        limits:
          cpus: 0.30
          memory: 10MB
  
  db:
    container_name: db
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=pyrinha
      - POSTGRES_USER=pyrinha
      - POSTGRES_PASSWORD=pyrinha
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 150MB
    command: >
      postgres
      -c fsync=off
      -c work_mem=64MB
      -c synchronous_commit=off
      -c wal_level=minimal
      -c max_wal_senders=0
    networks:
      - pyrinha
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pyrinha -d pyrinha" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  pyrinha:
    driver: bridge
  payment-processor:
    external: true