services:
  lb:
    image: nginx:alpine
    ports:
      - 9999:9999

    networks:
      - pyrinha
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - cache
    networks:
      - pyrinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "120MB"
    environment:
      DEFAULT_PAYMENT_PROCESSOR: "http://payment-processor-default:8080"
      FALLBACK_PAYMENT_PROCESSOR: "http://payment-processor-fallback:8080"

  api2:
    <<: *api
    ports:
      - 8082:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "120MB"

  cache:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - pyrinha
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"
    command: >
      redis-server
      --maxmemory 35mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
  
  db:
    container_name: db
    image: postgres:16-alpine
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "60MB"
    environment:
      - POSTGRES_SHARED_BUFFERS=16MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=32MB
    networks:
      - pyrinha
    command: >
      postgres
      -c shared_buffers=8MB
      -c effective_cache_size=16MB
      -c maintenance_work_mem=4MB
      -c work_mem=2MB
      -c max_connections=20
      -c fsync=off
      -c synchronous_commit=off
      -c wal_level=minimal
      -c max_wal_senders=0
      -c checkpoint_completion_target=0.9
      -c random_page_cost=1.1
      -c log_statement=none
      -c log_duration=off
      -c log_lock_waits=off

networks:
  pyrinha:
    driver: bridge
  payment-processor:
    external: true